### ISSUE TITLE
Add Prometheus metrics for retries

### ISSUE THREAD

**Issue by electron0zero** [grafana/synthetic-monitoring-agent#192]
Synthetic Monitoring Agent retries with backoff when sending logs and metrics. 

We have no visibility around these retries. Add Prometheus metrics around retries to gain more visibility.

https://github.com/grafana/synthetic-monitoring-agent/blob/61bb38d18764bc74d1fbae004a02925fc5f43e5b/internal/pkg/prom/prom.go#L55

https://github.com/grafana/synthetic-monitoring-agent/blob/61bb38d18764bc74d1fbae004a02925fc5f43e5b/internal/pkg/loki/loki.go#L13

**why do we want more visibility around these retries?**
We want to know when, and how many times we are retying, it will help us trace down issues with logs and metrics upstream services.

retries can also cause samples to arrive late, and if we have recording rules with short window on the synthetic monitoring metrics it will show no data.

**Comment by thepalbi** [comment]
Since this retry logic is being added, we could also add a metric for the 401 from gcom retry logic. I guess quantifying the number of sm-gcom-key-deleted errors we get can be useful, or getting an idea of how ofter it occurs:

https://github.com/grafana/synthetic-monitoring-agent/blob/main/internal/pusher/pusher.go#L118

**Comment by electron0zero** [comment]
@thepalbi we have `sm_agent_publisher_push_errors_total` metric with status tag, we push status code in that metric.

we can use sm_agent_publisher_push_errors_total to track 401 or other response codes we get back when publishing data. 

it was broken, sent a fix in https://github.com/grafana/synthetic-monitoring-agent/pull/279

**Comment by electron0zero** [comment]
fixed by #282
