### ISSUE TITLE
Newly added API_TOKEN is not working in grafana synthetic monitoring agent conf file.

### ISSUE THREAD

**Issue by parthi-kk** [grafana/synthetic-monitoring-agent#195]
Hello Team,

I have an issue with adding the newly generated API_TOKEN on my synthetic monitoring agent conf file.I tried to add the new API_TOKEN to enable my newly added probe location in synthetic monitoring but even after adding the token my probe location is showing offline.Kindly check and let me know how to add the multiple API_TOKENS in agent conf file.

Thanks

**Comment by electron0zero** [comment]
Hi 👋🏼,

1. can you share your config file with token redacted?

1. can you pass your API_TOKEN as a flag to synthetic-monitoring-agent, enable debug logs, and share what you are seeing

Here are steps to run agent using docker with debug logs, please modify these for your process.
```
# pull image
docker pull grafana/synthetic-monitoring-agent:latest
# export configs
# replace YOUR_TOKEN_HERE with your Authentication Token
export API_TOKEN=YOUR_TOKEN_HERE
export API_SERVER="synthetic-monitoring-grpc.grafana.net:443"
# run
docker run grafana/synthetic-monitoring-agent --api-server-address=${API_SERVER} --api-token=${API_TOKEN} --verbose=true
```

**Comment by parthi-kk** [comment]
Hello @electron0zero,


Inside my synthetic monitoring agent conf file under the parameter "API_TOKEN" I can be able to add my api token and related probe location to come online with 100% reachability. If I tried to generate and add another probe location api token, it won't come online.

My question is how to declare the two different probes tokens under the parameter "API_TOKEN"?

I have tried the following characters“,:;“ between the two tokens to differentiate them in the “API_TOKEN“ parameter but no luck.

Can you help me on this?

**Comment by electron0zero** [comment]
@parthi-kk you need to run a synthetic monitoring agent for each private probe. 

one synthetic monitoring agent can only run checks from one private probe so you can't supply multiple probe token to a probe.

If you are trying to run two probes, you need to run two synthetic monitoring agents.

**Comment by parthi-kk** [comment]
@electron0zero - Thank you for your update, but it is not a feasible one, right. Do we have any other options to declare different api_keys under the same conf file?

**Comment by electron0zero** [comment]
you can start multiple synthetic monitoring agent process each with diffrent token, and configure them to use a different token for each process with `--api-token` flag.

we recommend https://community.grafana.com/ for support questions :)
