### ISSUE TITLE
Unable to run the private probe with Synthetic Monitoring Agent

### ISSUE THREAD

**Issue by KrishnaJyothika** [grafana/synthetic-monitoring-agent#512]
Hi,

We have created the Private probe in grafana cloud account and trying to run it with synthetic monitoring agent docker public image. We are getting 404 error and API does not support required features error. 

docker run grafana/synthetic-monitoring-agent --api-server-address=synthetic-monitoring-api-us-west-0.grafana.net:443 --api-token='api-token' --verbose=true --debug

**Debug logs**

**{"level":"info","program":"synthetic-monitoring-agent","version":"v0.17.0-0-g0d702889","commit":"0d702889c43605527f5d95ed54a707bfea5b0e2f","buildstamp":"2023-09-05 17:15:40+00:00","features":"","change-log-level-enabled":false,"disconnect-enabled":false,"pprof-enabled":false,"time":1694596681889,"caller":"github.com/grafana/synthetic-monitoring-agent/cmd/synthetic-monitoring-agent/main.go:130","message":"starting"}
{"level":"info","program":"synthetic-monitoring-agent","time":1694596681889,"caller":"github.com/grafana/synthetic-monitoring-agent/cmd/synthetic-monitoring-agent/main.go:147","message":"disabling k6 checks"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] Channel created"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] original dial target is: \"synthetic-monitoring-api-us-west-0.grafana.net:443\""}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] parsed dial target is: {Scheme:synthetic-monitoring-api-us-west-0.grafana.net Authority: URL:{Scheme:synthetic-monitoring-api-us-west-0.grafana.net Opaque:443 User: Host: Path: RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] fallback to scheme \"passthrough\""}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] parsed dial target is: {Scheme:passthrough Authority: URL:{Scheme:passthrough Opaque: User: Host: Path:/synthetic-monitoring-api-us-west-0.grafana.net:443 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] Channel authority set to \"synthetic-monitoring-api-us-west-0.grafana.net\""}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] Resolver state updated: {\n  \"Addresses\": [\n    {\n      \"Addr\": \"synthetic-monitoring-api-us-west-0.grafana.net:443\",\n      \"ServerName\": \"\",\n      \"Attributes\": null,\n      \"BalancerAttributes\": null,\n      \"Type\": 0,\n      \"Metadata\": null\n    }\n  ],\n  \"ServiceConfig\": null,\n  \"Attributes\": null\n} (resolver returned new addresses)"}
{"program":"synthetic-monitoring-agent","subsystem":"http","time":1694596681890,"caller":"log/log.go:194","message":"Starting HTTP server on localhost:4050..."}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] Channel switches to new LB policy \"pick_first\""}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1 SubChannel #2] Subchannel created"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681890,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681891,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681891,"message":"2023/09/13 09:18:01 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address \"synthetic-monitoring-api-us-west-0.grafana.net:443\" to connect"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596681891,"message":"2023/09/13 09:18:01 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc00019a828, {CONNECTING <nil>}"}
2023/09/13 09:18:04 RequireTransportSecurity
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596684970,"message":"2023/09/13 09:18:04 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to READY"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596684970,"message":"2023/09/13 09:18:04 INFO: [core] pickfirstBalancer: UpdateSubConnState: 0xc00019a828, {READY <nil>}"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596684970,"message":"2023/09/13 09:18:04 INFO: [core] [Channel #1] Channel Connectivity change to READY"}
{"level":"info","program":"synthetic-monitoring-agent","subsystem":"updater","time":1694596684970,"caller":"github.com/grafana/synthetic-monitoring-agent/internal/checks/checks.go:313","message":"fetching check configuration from synthetic-monitoring-api"}
E: API does not support required features
{"level":"error","program":"synthetic-monitoring-agent","subsystem":"updater","error":"rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain\"","action":"registering probe with synthetic-monitoring-api","code":12,"time":1694596685288,"caller":"github.com/grafana/synthetic-monitoring-agent/internal/checks/checks.go:319","message":"unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain\""}
{"level":"info","program":"synthetic-monitoring-agent","subsystem":"updater","error":"API does not support required features","was_connected":false,"connection_state":"READY","time":1694596685288,"caller":"github.com/grafana/synthetic-monitoring-agent/internal/checks/checks.go:248","message":"broke out of loop"}
{"level":"error","program":"synthetic-monitoring-agent","subsystem":"updater","error":"API does not support required features","connection_state":"READY","time":1694596685288,"caller":"github.com/grafana/synthetic-monitoring-agent/internal/checks/checks.go:283","message":"cannot connect, bailing out"}
{"level":"info","program":"synthetic-monitoring-agent","subsystem":"signal handler","time":1694596685288,"caller":"github.com/grafana/synthetic-monitoring-agent/cmd/synthetic-monitoring-agent/main.go:284","message":"shutting down"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596685288,"message":"2023/09/13 09:18:05 INFO: [core] [Channel #1] Channel Connectivity change to SHUTDOWN"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596685288,"message":"2023/09/13 09:18:05 INFO: [core] [Channel #1] ccBalancerWrapper: closing"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596685288,"message":"2023/09/13 09:18:05 INFO: [core] [Channel #1] Closing the name resolver"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596685288,"message":"2023/09/13 09:18:05 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to SHUTDOWN"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596685288,"message":"2023/09/13 09:18:05 INFO: [core] [Channel #1 SubChannel #2] Subchannel deleted"}
{"program":"synthetic-monitoring-agent","component":"grpc-go","time":1694596685288,"message":"2023/09/13 09:18:05 INFO: [core] [Channel #1] Channel deleted"}**

Please help us resolve this.

**Comment by RuBiCK** [comment]
It seems you are using `backend address` instead of `API server URL` check this doc  https://grafana.com/docs/grafana-cloud/monitor-public-endpoints/private-probes/#probe-api-server-url hope it helps
