### ISSUE TITLE
Create an RPM repo and publish packages

### ISSUE THREAD

**Issue by brittenhouse** [grafana/synthetic-monitoring-agent#57]
Both .deb and .rpm packages are being created, but only .deb packages are delivered. An RPM repo needs to be created with packages pushed the same as for .deb.

**Comment by danfoxley** [comment]
Isn't this feature completed, or do I have it wrong?
https://github.com/grafana/synthetic-monitoring-agent/commit/7f850c21fa6040f6a2d8e4f6772ae5eb5b18f61b

**Comment by mem** [comment]
this is completed, yes
