### ISSUE TITLE
k6 checks - private probes can't access IPs in 10.0.0.0/8 private address range

### ISSUE THREAD

**Issue by peterschretlen** [grafana/synthetic-monitoring-agent#587]
When running k6 tests from the agent, we have hardcoded values for `--blacklist-ip` and `--block-hostnames`, and TODO to make these configurable. 

https://github.com/grafana/synthetic-monitoring-agent/blob/99a88d45475d021b7a1cd137f18fd4fdf7144d4b/internal/k6runner/k6runner.go#L409-L410

For private probes in particular we'd want to the option to allow private IP ranges like `10.0.0.0/8`

**Comment by The-9880** [comment]
Fix merged, closing issue.
