### ISSUE TITLE
Variables cannot be used in the body of MultiHTTP requests

### ISSUE THREAD

**Issue by peterschretlen** [grafana/synthetic-monitoring-agent#637]
The [docs](https://grafana.com/docs/grafana-cloud/monitor-public-endpoints/checks/multihttp/#variables) state:
> It’s possible to use this anywhere where a string is expected, for example as the value of a header or the value of an assertion

So it is reasonable to expect that you'd be able to use the variable value in the body of a request.  Say for example you have a variable `$token` with value `abc` from the previous request, you should be able to setup a POST request like this:
```
{
      "acceptance_token": "${token}"
}
```

And expect the body to be:
```
{
      "acceptance_token": "abc"
}
```

It appears we just [copy the body as-is](https://github.com/grafana/synthetic-monitoring-agent/blob/0a03a914d4e602e3a2693726a603f112767d472f/internal/prober/multihttp/script.go#L89-L106)

**Comment by pascal-arevalo** [comment]
Are there any updates on this? 😄
