### ISSUE TITLE
v0.24.0+ requires k6 to be initialized in Grafana Cloud

### ISSUE THREAD

**Issue by asreich** [grafana/synthetic-monitoring-agent#712]
I just tried updating the Synthetic Monitoring agent from 0.19.3 to 0.24.1 and ran into an issue which seems to be related to us not having initialized k6 in our dashboard yet. We do not currently have a need for it. This causes the pod to Crashloop and checks are not run. Please either provide a toggle or handle this transparently in the application startup.

**Comment by ka3de** [comment]
Hi @asreich , you can disable the `scripted` checks functionality in the probe settings page.
![Screenshot from 2024-05-31 09-44-57](https://github.com/grafana/synthetic-monitoring-agent/assets/6529572/d433ca59-bf20-4a7d-91fc-06b1b8db4246)

If you want to run scripted checks in the future, you will need to enable this feature for the probe in the API and also enable the capability in the agent through the features flag such as `--features=k6`.
