### ISSUE TITLE
Add section regarding Alerting to the plugin doc page 

### ISSUE THREAD

**Issue by simonc6372** [grafana/synthetic-monitoring-agent#85]
Add a section regarding Alerting to the main plugin docs page at 
https://grafana.com/grafana/plugins/grafana-synthetic-monitoring-app

probably linking to https://github.com/grafana/synthetic-monitoring-app/tree/master/docs/alerts 

And maybe also mentioning that to create alerts from grafana it self (not using prom alert manager) will require the user to create specific dashboards for each alert.

**Comment by electron0zero** [comment]
merged in master, changes should be live soon
