### ISSUE TITLE
Recent releases are missing assets

### ISSUE THREAD

**Issue by mem** [grafana/synthetic-monitoring-agent#956]
We changed something recently that caused assets to not be published correctly:

bad: v0.28.2: https://github.com/grafana/synthetic-monitoring-agent/releases/tag/v0.28.2
good: v0.26.0: https://github.com/grafana/synthetic-monitoring-agent/releases/tag/v0.26.0

**Comment by roobre** [comment]
Dropping some context: As a part of building linux packages, goreleaser used to sign them with a GPG key. That key is not trivially accessible from GHA using standard shared-workflows.

I asked platform about this in the past [here](https://raintank-corp.slack.com/archives/C0671T2J5CH/p1724764899694389), and they suggested `deployment_tools` would be the right place to do the signing, and what everybody else publishing packages is doing.
